name: Release Slack Message
on:
  release:
    types: [published]

jobs:
  post-slack-message:
    name: Post Slack Message
    runs-on: ubuntu-latest
    steps:
    - name: "Post to internal #releases"
      id: internal_release
      uses: slackapi/slack-github-action@v1.18.0
      with:
        channel-id: ${{ secrets.RELEASE_SLACK_CHANNEL }}
        slack-message: "Redpanda release ${{ github.event.release.tag_name }} has been published: ${{ github.event.release.html_url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
